.TH impasto 1 "August 2026" "The Impasto Project" "Impasto"
.SH NAME
Impasto \- simple image editor
.SH SYNOPSIS
.B impasto
.I [<file_name>]
.SH DESCRIPTION
Impasto is a drawing/editing program, forked from Pinta, that provides a
simplified alternative to the GIMP for casual users.
.PP
Features include:
.PP
 - Adjustments (Auto level, Black and White, Sepia, …)
 - Multiple layers
 - Unlimited undo/redo
 - Drawing tools (Paintbrush, Pencil, Shapes, …)
.SH OPTIONS
.TP
.B file_name
Optional. The name of the image file for Impasto to open.
.SH AUTHOR
Impasto is a fork of Pinta \fBhttps://github.com/PintaProject/Pinta\fR, which
was created by Jonathan Pobst <monkey@jpobst.com> and the Pinta project
contributors. For a complete list of contributors, refer to the \fBAbout\fR
option in the \fBHelp\fR menu.
.SH BUGS
Please submit bugs to \fBhttps://github.com/zbcoding/ImpastoPaint/issues\fR.
