<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Addins.CecilReflector" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Mono.Addins.Setup" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
